/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LotdpLotdpIdRouteImport } from './routes/lotdp.$lotdpId'
import { Route as AddressGnafIdRouteImport } from './routes/address.$gnafId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LotdpLotdpIdRoute = LotdpLotdpIdRouteImport.update({
  id: '/lotdp/$lotdpId',
  path: '/lotdp/$lotdpId',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressGnafIdRoute = AddressGnafIdRouteImport.update({
  id: '/address/$gnafId',
  path: '/address/$gnafId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address/$gnafId': typeof AddressGnafIdRoute
  '/lotdp/$lotdpId': typeof LotdpLotdpIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address/$gnafId': typeof AddressGnafIdRoute
  '/lotdp/$lotdpId': typeof LotdpLotdpIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/address/$gnafId': typeof AddressGnafIdRoute
  '/lotdp/$lotdpId': typeof LotdpLotdpIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/address/$gnafId' | '/lotdp/$lotdpId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/address/$gnafId' | '/lotdp/$lotdpId'
  id: '__root__' | '/' | '/address/$gnafId' | '/lotdp/$lotdpId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressGnafIdRoute: typeof AddressGnafIdRoute
  LotdpLotdpIdRoute: typeof LotdpLotdpIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotdp/$lotdpId': {
      id: '/lotdp/$lotdpId'
      path: '/lotdp/$lotdpId'
      fullPath: '/lotdp/$lotdpId'
      preLoaderRoute: typeof LotdpLotdpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/$gnafId': {
      id: '/address/$gnafId'
      path: '/address/$gnafId'
      fullPath: '/address/$gnafId'
      preLoaderRoute: typeof AddressGnafIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressGnafIdRoute: AddressGnafIdRoute,
  LotdpLotdpIdRoute: LotdpLotdpIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
